version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - BASE_IMAGE=ubuntu:20.04
        - BASE_RUNTIME_IMAGE=ubuntu:20.04
        - ONNXRUNTIME_VERSION=1.13.1
        - TARGETPLATFORM=linux/amd64,linux/arm64/v8
        - USE_GPU=false
    ports:
      - "50021:50021"
    environment:
      OPENAI_KEY: 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
    